/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class TenantAuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorId', 'actorType', 'createdAt', 'id', 'ipAddress', 'metadata', 'tenantId'] as const
  $columns = TenantAuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorId: string | null
  @column()
  declare actorType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any | null
  @column()
  declare tenantId: string | null
}

export class TenantBrandingSchema extends BaseModel {
  static $columns = ['createdAt', 'emailFooter', 'fromEmail', 'fromName', 'id', 'logoUrl', 'primaryColor', 'supportUrl', 'tenantId', 'updatedAt'] as const
  $columns = TenantBrandingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare emailFooter: any | null
  @column()
  declare fromEmail: string | null
  @column()
  declare fromName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare logoUrl: string | null
  @column()
  declare primaryColor: string | null
  @column()
  declare supportUrl: string | null
  @column()
  declare tenantId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TenantFeatureFlagSchema extends BaseModel {
  static $columns = ['config', 'createdAt', 'enabled', 'flag', 'id', 'tenantId', 'updatedAt'] as const
  $columns = TenantFeatureFlagSchema.$columns
  @column()
  declare config: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column()
  declare flag: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare tenantId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TenantMetricSchema extends BaseModel {
  static $columns = ['bandwidthBytes', 'createdAt', 'errorCount', 'id', 'period', 'requestCount', 'tenantId'] as const
  $columns = TenantMetricSchema.$columns
  @column()
  declare bandwidthBytes: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorCount: bigint | number
  @column({ isPrimary: true })
  declare id: string
  @column.date()
  declare period: DateTime
  @column()
  declare requestCount: bigint | number
  @column()
  declare tenantId: string
}

export class TenantSsoConfigSchema extends BaseModel {
  static $columns = ['clientId', 'clientSecret', 'createdAt', 'enabled', 'id', 'issuerUrl', 'provider', 'redirectUri', 'scopes', 'tenantId', 'updatedAt'] as const
  $columns = TenantSsoConfigSchema.$columns
  @column()
  declare clientId: string
  @column()
  declare clientSecret: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare issuerUrl: string
  @column()
  declare provider: string
  @column()
  declare redirectUri: string
  @column()
  declare scopes: any
  @column()
  declare tenantId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TenantWebhookDeliverySchema extends BaseModel {
  static $columns = ['attempt', 'createdAt', 'event', 'id', 'nextRetryAt', 'payload', 'responseBody', 'status', 'statusCode', 'webhookId'] as const
  $columns = TenantWebhookDeliverySchema.$columns
  @column()
  declare attempt: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare event: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare nextRetryAt: DateTime | null
  @column()
  declare payload: any
  @column()
  declare responseBody: string | null
  @column()
  declare status: string
  @column()
  declare statusCode: number | null
  @column()
  declare webhookId: string
}

export class TenantWebhookSchema extends BaseModel {
  static $columns = ['createdAt', 'enabled', 'events', 'id', 'secret', 'tenantId', 'updatedAt', 'url'] as const
  $columns = TenantWebhookSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column()
  declare events: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare secret: string | null
  @column()
  declare tenantId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare url: string
}

export class TenantSchema extends BaseModel {
  static $columns = ['createdAt', 'customDomain', 'deletedAt', 'email', 'id', 'metadata', 'name', 'status', 'updatedAt'] as const
  $columns = TenantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customDomain: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metadata: any | null
  @column()
  declare name: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
