/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CarMakeSchema extends BaseModel {
  static $columns = ['country', 'createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = CarMakeSchema.$columns
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CarModelSchema extends BaseModel {
  static $columns = ['bodyType', 'createdAt', 'id', 'makeId', 'name', 'updatedAt'] as const
  $columns = CarModelSchema.$columns
  @column()
  declare bodyType: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare makeId: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
