{{- if not .Values.app.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lasagna-app.fullname" . }}-secrets
  labels:
    {{- include "lasagna-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.app.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
